### ISSUE TITLE
Can I substitute this for netrw when opening a directory from terminal?

### ISSUE THREAD

**Issue by mdxprograms** [philip-karlsson/bolt.nvim#8]
Not really an issue, but I was curious if there is a way to open this when I do something along the lines of `nvim .` in a project directory and have bolt open by default?

btw fantastic plugin. I've been using it quite a bit lately.

**Comment by ripxorip** [comment]
Hi thanks for the kind words! I like the idea, I am currently on my honeymoon but I will take a look when I get home in a couple of days. Should definitely be possible and I can see the use case.

**Comment by mdxprograms** [comment]
well congrats! :tada: 
Sounds great, enjoy your honeymoon :smiley:

**Comment by ripxorip** [comment]
Thank you very much :) What would characterize a project directory? A .git folder?

**Comment by mdxprograms** [comment]
Ya that seems to be a good default

**Comment by ripxorip** [comment]
Without any changes to the plugin, you could do like this:

`nvim . -c "Tc"`

Bind that to an alias (I will do that myself) and you should get the desired behavior? :)
